module.exports = {
  validateEmail: require("./validateEmail"),
  validatePassword: require("./validatePassword"),
  validateCallback: require("./validateCallback"),
  validateText: require("./validateText"),
  validateVisibility: require("./validateVisibility"),
  validateFormId: require("./validateFormId"),
  validateQuestionType: require("./validateQuestionType"),
  validateFavoritesAction: require("./validateFavoritesAction"),
  validateHost: require("./validateHost"),
  validateQuestionId: require("./validateQuestionId"),
  validatePin: require("./validatePin"),
  validateString: require("./validateString"),
  validateNumber: require("./validateNumber"),
  validateTimeLimit: require("./validateTimeLimit"),
  validateMCQAnswer: require("./validateMCQAnswer"),
};
